### ISSUE TITLE
学习请教

### ISSUE THREAD

**Issue by chirmy** [QR-0W/SDUWH_2023_MachineLearning#1]
hello, 大佬， 我最近看到了你的这个项目，感觉很有意思，在run的过程中遇到了困难，请问方便指导一下吗？ 方便的话麻烦您加一下我qq:1838844593 或者您给我您的联系方式我来加您也行，谢谢啦！

**Comment by QR-0W** [comment]
> hello, 大佬， 我最近看到了你的这个项目，感觉很有意思，在run的过程中遇到了困难，请问方便指导一下吗？ 方便的话麻烦您加一下我qq:1838844593 或者您给我您的联系方式我来加您也行，谢谢啦！

已添加。我并非人工智能专业学生，只是正在学习。而且学校比较忙。所以只能尽量尝试解答。
